In [1]:
import numpy as np
import pandas as pd

In [4]:
a=np.array([[2,3,4],[5,6,7]])


In [5]:
a


array([[2, 3, 4],
       [5, 6, 7]])

In [14]:
a=np.array([9,5,0])
a.shape

(3,)

In [8]:
a

array([[0, 0, 0]])

In [26]:
a[0]
a[:0]

array([], dtype=int64)

In [28]:
a.ndim


1

In [30]:
a.shape

(3,)

In [31]:
a.dtype

dtype('int64')

In [33]:
np.zeros(3)

array([0., 0., 0.])

In [38]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.arange(3)

array([0, 1, 2])

n

In [41]:
np.arange(3,24,9)

array([ 3, 12, 21])

In [47]:
np.linspace(0,20,num=50)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [48]:
np.sort(a)

array([0, 5, 9])

In [50]:
a = np.array([2,3,4,5])
b = np.array([8,6,7,4])

In [51]:
np.concatenate((a,b))

array([2, 3, 4, 5, 8, 6, 7, 4])

In [53]:
x = np.array([[2,3],[7,8]])
y = np.array([[5,9]])



In [54]:
np.concatenate((x,y))

array([[2, 3],
       [7, 8],
       [5, 9]])

In [56]:
a = np.arange(8)

In [57]:
print(a)

[0 1 2 3 4 5 6 7]


In [58]:
b = a.reshape(4,2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [62]:
a=a.flatten()

In [63]:
a.shape

(8,)

In [61]:
np.square(a)

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [64]:
np.save('d1',a)

In [65]:
np.load('d1.npy')

array([0, 1, 2, 3, 4, 5, 6, 7])

In [66]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [67]:
np.save('d2',a)

In [68]:
np.load('d2.npy')

array([0, 1, 2, 3, 4, 5, 6, 7])